[2021-08-16 15:47:27,330] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_complex.lookup_entry_result 2021-08-16T15:43:47.414310+00:00 [queued]>
[2021-08-16 15:47:27,705] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_complex.lookup_entry_result 2021-08-16T15:43:47.414310+00:00 [queued]>
[2021-08-16 15:47:27,740] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-08-16 15:47:27,765] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-08-16 15:47:27,767] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-08-16 15:47:27,975] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): lookup_entry_result> on 2021-08-16T15:43:47.414310+00:00
[2021-08-16 15:47:28,048] {standard_task_runner.py:52} INFO - Started process 407 to run task
[2021-08-16 15:47:28,176] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_complex', 'lookup_entry_result', '2021-08-16T15:43:47.414310+00:00', '--job-id', '40', '--pool', 'default_pool', '--raw', '--subdir', '/home/airflow/.local/lib/python3.6/site-packages/airflow/example_dags/example_complex.py', '--cfg-path', '/tmp/tmpcfyq4fmz', '--error-file', '/tmp/tmphqjr9wiu']
[2021-08-16 15:47:28,258] {standard_task_runner.py:77} INFO - Job 40: Subtask lookup_entry_result
[2021-08-16 15:47:31,920] {logging_mixin.py:104} INFO - Running <TaskInstance: example_complex.lookup_entry_result 2021-08-16T15:43:47.414310+00:00 [running]> on host 8f195762143d
[2021-08-16 15:47:32,456] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_complex
AIRFLOW_CTX_TASK_ID=lookup_entry_result
AIRFLOW_CTX_EXECUTION_DATE=2021-08-16T15:43:47.414310+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-16T15:43:47.414310+00:00
[2021-08-16 15:47:32,474] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-08-16 15:47:32,477] {bash.py:158} INFO - Running command: echo lookup_entry_result
[2021-08-16 15:47:32,585] {bash.py:169} INFO - Output:
[2021-08-16 15:47:32,588] {bash.py:173} INFO - lookup_entry_result
[2021-08-16 15:47:32,600] {bash.py:177} INFO - Command exited with return code 0
[2021-08-16 15:47:32,691] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=example_complex, task_id=lookup_entry_result, execution_date=20210816T154347, start_date=20210816T154727, end_date=20210816T154732
[2021-08-16 15:47:33,287] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-08-16 15:47:33,300] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 407
[2021-08-16 15:47:33,701] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-08-16 15:47:33,704] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2021-08-16 15:47:33,846] {process_utils.py:66} INFO - Process psutil.Process(pid=407, status='terminated', exitcode=1, started='15:47:27') (407) terminated with exit code 1
